### ISSUE TITLE
Phoenix 1.3.4 cannot use phoenix_html ~> 2.11

### ISSUE THREAD

**Issue by mgwidmann** [phoenixframework/phoenix_html#229] opened 2018-08-31 02:29 UTC
```
Failed to use "plug" (version 1.4.5) because
  phoenix (version 1.3.4) requires ~> 1.3.3 or ~> 1.4
  phoenix_html (version 2.12.0) requires ~> 1.5
  mix.exs specifies ~> 1.4

** (Mix.Error) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
    (mix) lib/mix.ex:323: Mix.raise/1
    (hex) lib/hex/remote_converger.ex:60: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix) lib/mix/tasks/deps.get.ex:28: Mix.Tasks.Deps.Get.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
```

Caused by this change:
https://github.com/phoenixframework/phoenix_html/commit/59963b904dfab69c1c6ab2e4dfb21590b4f65577#diff-6023be6004fce4718dad3dafb576d258L30

If phoenix cannot be updated can phoenix_html be relaxed?

**Comment by mgwidmann** [comment] 2018-08-31 02:30
Workaround as instructed in the error message works, adding `{:plug, "~> 1.5", override: true}` to `deps()` resolves the issue.

**Comment by josevalim** [comment] 2018-08-31 06:00
It seems like “mix deps.update plug” should also work, since there are plug
versions that match all requirements.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment] 2018-09-03 06:31
I will go ahead and close this as there should be compatible versions without overrides by running `mix deps.update plug`. If that doesn't work, then it is most likely a Hex/Mix bug, which we would need more information to reproduce. Thanks!

**Closed by josevalim** 2018-09-03 06:31 UTC
