### ISSUE TITLE
Strange compilation warning on elixir 1.11

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix_html#321] opened 2020-10-26 14:28 UTC
# Versions
phoenix_html version: 2.14.2
phoenix version: 1.5.6
elixir: 1.11.1
otp: 23.1.1

# To reproduce:
In phoenix umbrella app
1. mix compile
2. mix deps.clean phoenix_html
3. mix deps.get
4. mix compile

# Result:
```
==> phoenix_html
Compiling 8 files (.ex)
warning: Phoenix.HTML.Safe.Map.__impl__/1 defined in application :my_app_web is used by the current application but the current application does not directly depend on :my_app_web. To fix this, you must do one of:

  1. If :my_app_web is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :my_app_web is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :merchant_panel, you may optionally skip this warning by adding [xref: [exclude: Phoenix.HTML.Safe.Map]] to your "def project" in mix.exs

  lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for/1

Generated phoenix_html app
```

The warning does not show up on first compilation.

**Comment by josevalim** [comment] 2020-10-26 14:31
Interesting, I can't get this warning in my app (same versions, also umbrella). Can you please provide a minimal mix.exs that reproduces it? Thanks!

**Comment by lukaszsamson** [comment] 2020-10-26 15:27
Sorry @josevalim, I forgot to mention that the app defines `Phoenix.HTML.Safe` protocol implementation for `Map`
```
defimpl Phoenix.HTML.Safe, for: Map do
  def to_iodata(data), do: data |> Jason.encode!(pretty: true) |> Plug.HTML.html_escape()
end
```

**Comment by josevalim** [comment] 2020-10-26 15:29
I just sprinkled that in my app, force recompiled it, and I still cannot reproduce it.  :) Please try to isolate it!

**Comment by lukaszsamson** [comment] 2020-10-26 15:39
This reproduces it on my machine (macOS): https://github.com/lukaszsamson/phoenix_html_bug_repro
It's a vanilla `mix phx.new hello --umbrella` with the protocol implementation added.

**Comment by joelparkerhenderson** [comment] 2020-11-02 09:42
My team is seeing a similar kind of error message about dependencies, for an entirely different area of our app, just after upgrading GitHub actions from OTP 23.x to 23.1.1:
```
diff --git a/.github/workflows/mix-tests.yml b/.github/workflows/mix-tests.yml
-          otp-version: '23.x'
+          otp-version: '23.1.1'
```

In our app, all the warnings are about a recently-added resource. We'll update this post as I learn more, likely today.

**Comment by josevalim** [comment] 2020-11-02 10:13
@joelparkerhenderson are you also seeing it happening for `__impl__` function calls or for other ones? The Erlang upgrade can be a red herring... it simply causes deps to be recompiled, which would cause the warning.

**Comment by joelparkerhenderson** [comment] 2020-11-02 10:37
Thanks Jose for such a fast response. May I hire you to take a look at our private repo so you can see the real code that's causing the warning? Or donate to your favorite charity?

My contact info is joel@joelparkerhenderson.com +1-415-317-2700 (both are public) and this is for a Y Combinator company.

**Comment by josevalim** [comment] 2020-11-02 10:55
Hi @joelparkerhenderson, thanks for the kind offer! I think there is a chance we can resolve this quickly before resorting to other options.

There are a couple options here:

1. You are getting warnings that look like this one: `warning: MOD.__impl__/1 defined in application :xyz` - the important question is: is the warning accusing an error in the `__impl__` function? If so, it is a bug in Elixir which I just fixed in master.

2. If you are getting this warning because you have an umbrella app, then you need to make sure that if umbrella child `:a` is using a module `B.Example` defined in application `:b`, then you need to make sure application `:a` depends on application `:b` in your mix.exs like this: `{:b, in_umbrella: true}`.

If you have a different scenario, let me know!

**Comment by josevalim** [comment] 2020-11-02 10:55
In any case, the original issue has been fixed in Elixir master and v1.11. Joel, let's continue the convo here and then upgrade to private if necessary. :)

**Closed** 2020-11-02 10:56 UTC

**Comment by joelparkerhenderson** [comment] 2020-11-02 11:33
Much obliged. Different scenario possibly. 

The warnings do not contain `__impl__` as far as I can tell. We do configure the umbrella child as you describe. 

I just now upgraded to 1.11 by editing `mix-tests.yml`
         with:                                                                                                                         
-          otp-version: '23.x'                                                                                                         
-          elixir-version: '1.11.0'                                                                                                    
+          otp-version: '23.1.1'                                                                                                       
+          elixir-version: '1.11.1'    
```

I'm now seeing similar warnings in dependencies, including public dependencies:

```
==> oauther
Compiling 1 file (.ex)
warning: :crypto.hmac/3 defined in application :crypto is used by the current application but the current application does not directly depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs

  lib/oauther.ex:64: OAuther.signature/4

==> pow
Compiling 116 files (.ex)
warning: :mnesia.add_table_copy/3 defined in application :mnesia is used by the current application but the current application does not directly depend on :mnesia. To fix this, you must do one of:

  1. If :mnesia is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :mnesia is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :mnesia, you may optionally skip this warning by adding [xref: [exclude: :mnesia]] to your "def project" in mix.exs

  lib/pow/store/backend/mnesia_cache.ex:389: Pow.Store.Backend.MnesiaCache.sync_table/2
```

**Comment by josevalim** [comment] 2020-11-02 11:42
Hi @joelparkerhenderson! Those are definitely bugs in your dependencies that the compiler is now catching. :) For example, if you used oauther in your app and nothing brought `:crypto` as a dependency, once you built a release you would have a broken software because the `:crypto` application could be missing. I recommend reporting those upstreams (or even sending a PR).  The oauther fix should be easy, it is a matter of adding `:crypto` to extra_applications. The Pow one may be more complicated as mnesia seems to be an optional dependency. So they will need to follow step 3 of the warning.

**Comment by joelparkerhenderson** [comment] 2020-11-02 12:22
Good info thanks. Given the above, I'm good hiring you to look at our app, and to do a blog post that helps developers with these new warnings. This is because I understand the warnings are powerful and valuable, and I also see they will surprise developers. Paying for your help here is a way that I can help fund open source, and your work on it, and also make progress with my team.

**Comment by josevalim** [comment] 2020-11-02 12:25
@joelparkerhenderson, please reach out to us via the dashbit.co website or via the e-mail in my profile. We will be glad to start a conversation around this topic but note that we are fully booked at the moment. Thanks for reaching out!
