### ISSUE TITLE
multiple_select breaks trying to render when updating/creating with errors

### ISSUE THREAD

**Issue by enoliglesias** [phoenixframework/phoenix_html#174] opened 2017-09-13 14:29 UTC
Hi! This week I've working with `multiple_select` and I found something weird, I think.

First of all, my versions:
```
phoenix, "1.3.0"
phoenix_ecto, "3.2.3"
phoenix_html, "2.10.4"
ecto, "2.1.6"
```

**The explanation:**

I have a couple of models that are related through a `many_to_many` relation. `Job` and `Category`.

I'm going to continue the explanation only with the `Job` model, but the bug happens in both ways. So in my `Job` model schema I have the following:

```elixir
schema "jobs" do
  field :title, :string

  timestamps()

  many_to_many :categories, App.Category, join_through: "categories_jobs", on_delete: :delete_all, on_replace: :delete
end
```

Then, my changeset:

```elixir
def changeset(struct, params \\ %{}) do
  struct
  |> cast(params, [:title])
  |> validate_required([:title])
  |> put_assoc(:categories, parse_categories(params))
end

defp parse_categories(params)  do
  (params["categories"] || [])
  |> Enum.map(&(Repo.get_by(App.Category, id: &1))
end
```

Now, I added a `multiple_select` to my form, this way:

```elixir
<%= multiple_select f, :categories, categories_options(), selected: selected_categories_ids(@changeset, @conn), class: "form-control" %>
```

The auxiliar functions stored in my `JobView`:
_selected_categories_ids_
```elixir
def selected_categories_ids(changeset, conn) do
  get_in(conn.params, ["job", "categories"]) || Enum.map(changeset.data.categories, &(&1.id))
end
```

_categories_options_
```elixir
def categories_options do
  query = from category in App.Category,
    select: {category.title, category.id}
  Repo.all(query)
end
```

**The problem:**

As you see, my model only have a title (required) and the `multiple_select` for the categories. If I send **all** the info in the form, everything works fine.

But, if I select some categories, leaving the title blank and I send the form. When it tries to render the form with the title error info, etc. I get the following error:

```
protocol Phoenix.HTML.Safe not implemented 
for %App.Category{__meta__: #Ecto.Schema.Metadata<:loaded, "categories">, categories: [%App.Category{__meta__: #Ecto.Schema....
[...]
```

**The weird thing:**

Navigating through the `phoenix_html` code, I found that in the `selected` method (https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L843) which is used in the `multiple_select` (https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L940) it accepts the `:value` key too. So in my despair 😅  I try to use it, and it works!

So, if I use: 
```elixir
<%= multiple_select f, :categories, categories_options(), value: selected_categories_ids(@changeset, @conn), class: "form-control" %>
````

Instead of:
```elixir
<%= multiple_select f, :categories, categories_options(), selected: selected_categories_ids(@changeset, @conn), class: "form-control" %>
```

Everything works as expected.

I read in the documentation that:
```
The :selected option will mark the given IDs as selected unless the form is being resubmitted. When resubmitted, it uses the form params as values.
```

But if they take the params when I resubmitting, it would be impossible to get that error. I'm not modifying the params, they are an array of ids.

I can't understand what may be happening. What do you think?

Thanks in advance! x)

**Comment by josevalim** [comment] 2017-09-13 15:33
I can't see what is wrong as well. Can you print what is the value returned by `selected_categories_id` in case you get an error? You should be able to do it by simply wrapping it in `IO.inspect` like this:  `selected: IO.inspect(selected_categories_ids(@changeset, @conn))`. The value will be in your terminal.

**Comment by enoliglesias** [comment] 2017-09-13 17:16
@josevalim  Thanks for the quick response.

First of all, the output of the `IO.inspect`:
```elixir
<%= multiple_select f, :categories, categories_options(), selected: IO.inspect(selected_categories_ids(@changeset, @conn)), class: "form-control" %>
```
`["3", "1", "2"]`

Now, the backtrace. I omit some concrete "private" data of our application:
```
[info] POST /jobs/1
[...]
[debug] Processing with App.JobController.update/2
  Parameters: %{"_csrf_token" => "XXX", "_method" => "put", "_utf8" => "✓", "id" => "1", "job" => %{"categories" => ["3", "1", "2"], "title" => ""}}
  Pipelines: [:browser, :browser_session, :locale, :authenticated_user]
[...]
[debug] QUERY OK source="categories" db=0.2ms
SELECT j0."title", j0."id" FROM "categories" AS j0 []
["3", "1", "2"]
[info] Sent 500 in 42ms
[error] #PID<0.5684.0> running App.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /jobs/1
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Hcmex.Category{__meta__: #Ecto.Schema.Metadata<:loaded, "categories">, id: 3, inserted_at: ~N[2017-09-07 13:43:02.300362]...
    [...]
        (phoenix_html) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
        (phoenix_html) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
        (phoenix_html) lib/phoenix_html.ex:151: Phoenix.HTML.html_escape/1
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (phoenix_html) lib/phoenix_html/form.ex:948: Phoenix.HTML.Form.multiple_select/4
        (hcmex) web/templates/job/form.html.eex:22: anonymous fn/2 in App.JobView.form.html/1
        (phoenix_html) lib/phoenix_html/form.ex:253: Phoenix.HTML.Form.form_for/4
        (hcmex) web/templates/job/form.html.eex:1: App.JobView."form.html"/1
        (hcmex) web/templates/job/edit.html.eex:10: App.JobView."edit.html"/1
        (hcmex) web/templates/layout/app.html.eex:23: App.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (hcmex) web/controllers/job_controller.ex:1: App.JobController.action/2
        (hcmex) web/controllers/job_controller.ex:1: App.JobController.phoenix_controller_pipeline/2
        (hcmex) lib/hcmex/endpoint.ex:1: App.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (hcmex) lib/hcmex/endpoint.ex:1: App.Endpoint.plug_builder_call/2
        (hcmex) lib/plug/debugger.ex:99: App.Endpoint."call (overridable 3)"/2
        (hcmex) lib/hcmex/endpoint.ex:1: App.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
```

You can see the `IO.inspect` output and just after the error.

In order to try to give you more information, I tried to inspect the whole input with the `value` version:
```elixir
<% IO.inspect multiple_select f, :categories, categories_options(), value: selected_categories_ids(@changeset, @conn), class: "form-control" %>
```

And it returns:

```
{:safe,
 [60, "select",
  [[32, "class", 61, 34, "form-control", 34],
   [32, "id", 61, 34, "categories_jobs", 34],
   [32, "multiple", 61, 34, "", 34],
   [32, "name", 61, 34, "job[categories][]", 34]], 62,
  [[["", 60, "option",
     [[32, "selected", 61, 34, "selected", 34], [32, "value", 61, 34, "3", 34]],
     62, "Category 1", 60, 47, "option", 62], 60, "option",
    [[32, "selected", 61, 34, "selected", 34], [32, "value", 61, 34, "1", 34]],
    62, "Category 2", 60, 47, "option", 62], 60, "option",
   [[32, "selected", 61, 34, "selected", 34], [32, "value", 61, 34, "2", 34]],
   62, "Category 3", 60, 47, "option", 62], 60, 47, "select", 62]}
```
The version with `select` can't be "inspect" because of the error.

**Comment by josevalim** [comment] 2017-09-13 17:22
Can you please try this:

```elixir
<% multiple_select f, :categories, categories_options(), selected: IO.inspect(selected_categories_ids(@changeset, @conn)), class: "form-control" %>
```

It should show the inspect result before you get the error

**Comment by enoliglesias** [comment] 2017-09-13 17:25
Yep, I put it in the previous comment 😝 

```elixir
<%= multiple_select f, :categories, categories_options(), selected: IO.inspect(selected_categories_ids(@changeset, @conn)), class: "form-control" %>
```

Returns:
`["3", "1", "2"]`

**Comment by josevalim** [comment] 2017-09-13 18:22
Oh, sorry, I missed it somehow! 🙈 

Ok, I officially do not understand how you can get the error above. Do you have a simple app that reproduces the issue?

**Comment by enoliglesias** [comment] 2017-09-14 05:57
I think I have to apologize. I created this repo (https://github.com/enoliglesias/multiple_select_example). And it worked fine. In view of that, it was clear that I had something wrong in my proyect. So I've tried deleting the `_build` folder to compile all over again from scratch. And it seems that it has been solved.

I'm sorry I wasted your time. Thank you!

**Comment by josevalim** [comment] 2017-09-14 09:25
No problem, thanks for following up!

**Comment by josevalim** [comment] 2017-09-14 09:26
Btw, which Elixir version are you running on?

**Closed by josevalim** 2017-09-14 09:25 UTC

**Comment by enoliglesias** [comment] 2017-09-14 10:02
Actually we're using 1.4.2

**Comment by josevalim** [comment] 2017-09-14 10:17
@enoliglesias if you are using umbrellas, we had some fixes regarding consolidation pushed to v1.5 but I would recommend at least running v1.4.5 (or v1.4.6), whatever is the latest on the v1.4 branch.

**Comment by enoliglesias** [comment] 2017-09-14 10:24
@josevalim thanks!! In fact, we're planning an upgrade to 1.5 😄

**Comment by matteo-gheri-pocketworks** [comment] 2020-04-06 15:34
Hello everyone,

Sorry to open an old issue, but I'm having an issue that I think is related to this one.
As enoliglesias, I have problems with the HTML.safe protocol (for the category model) when I try to update the model with invalid date, thus redirect to the edit page with changeset errors.

```
<%= multiple_select f, :categories, 
      entities_for_select(@categories, :name), 
      selected: Enum.map(selected_categories, &(&1.id)),
      class: "form-control select2" %>
<%= error_tag f, :categories %>
```

I've inspected both 'entities_for_select' and 'Enum.map(selected_categories, &(&1.id))' and they return the correct values even when I get the error. Indeed at the moment I resolved the issue just using "plain" html

```
<select class="form-control select2" name="food[categories][]" multiple>
    <%= for cat <- entities_for_select(@categories, :name) do %>
        <option value="<%= Keyword.get(cat, :value) %>" <%= if Enum.any?(selected_categories, fn x -> x.id == Keyword.get(cat, :value) end), do: "selected" %>> 
            <%= Keyword.get(cat, :key) %> 
        </option>
    <% end %>
</select>
```

Somehow the issue seems related to the changeset of the food model, because If I remove this from the changeset the error disappear:

`|> put_assoc(:categories, categories, required: true)`

Same things is happening with the food's tags (another many_to_many relation). 

Thank you!
