### ISSUE TITLE
Showing errors for fields inside `inputs_for` doesn't work

### ISSUE THREAD

**Issue by JustMikey** [phoenixframework/phoenix_html#25] opened 2015-08-23 12:30 UTC
I get this -> `could not generate inputs for :profile. Check the field exists and it is one of embeds_* or has_*`

Steps to reproduce the error: 

1) Pull this -> https://github.com/JustMikey/phoenix-test-app

2) Run `mix deps update --all` to get the latest `ecto` and run the migrations

3) Go to `/registration`

4) Create any user and remember it's username

5) Open the form again

6) Enter some other email, password, password confirmation and the same username you used in the previous form (so you'd get an error that this username is already taken)

7) Submit

**Comment by josevalim** [comment] 2015-08-23 14:13
I can't reproduce this as well. Using the same versions as you.

**Comment by josevalim** [comment] 2015-08-23 14:14
Nevermind, I forgot to migrate. :D

**Comment by JustMikey** [comment] 2015-08-23 16:14
@josevalim it's ok :)

**Comment by josevalim** [comment] 2015-08-23 22:18
Fixed in Ecto master! :D

**Closed** 2015-08-23 22:18 UTC
