### ISSUE TITLE
Phoenix.HTML.Link.link do...end block renders weird characters

### ISSUE THREAD

**Issue by jnmandal** [phoenixframework/phoenix_html#186] opened 2017-11-24 16:04 UTC
Looking at the source, I'm not sure if this is a bug or a feature but currently when you do something like:

```
<%= link to: user_path(@conn, :new) do %>
  <button class="btn btn-primary">Add customer</button>
<%= end %>
```
(I've recently learned its wrong semantically to use button inside link but just to humor example)

You will end up with a whitespace character in the generated markup coming from the newline. This character will be visible to user if text-decoration attribute is not `none`. Ie:

![screen shot 2017-11-24 at 10 22 00 am](https://user-images.githubusercontent.com/7440196/33217614-9c3b425c-d106-11e7-8de2-68c7ce5b413b.png)

The result is that you end up needing to write your code all on one line as:
```
<%= link to: user_path(@conn, :new) do %><button class="btn btn-primary">Add customer</button><%= end %>
```

To me this defeats the purpose of having that function accept a block. I'd like to propose that the function at https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/link.ex#L76-L78 -- which is responsible for transposing the block into a text -- somehow strip the whitespace. Not sure if this would go against intended design so wanted to post here first.

**Comment by josevalim** [comment] 2017-11-26 15:06
I cannot actually reproduce it on top of bootstrap (or on a simpler fiddle): https://jsfiddle.net/DTcHh/39645/

Maybe there is a CSS property, such as white-space, that is causing it to be shown?

**Comment by Gazler** [comment] 2017-11-27 08:36
Pretty sure this can be attributed to `text-decoration: underline` - this is default on hover with Bootstrap.

**Comment by Gazler** [comment] 2017-11-27 08:58
@josevalim This replicates it when you add a 2nd button. https://jsfiddle.net/DTcHh/39733/

**Comment by josevalim** [comment] 2017-11-27 16:19
Isn't the issue here is that you are using block elements (button) inside inline elements (a)? If I change `a` to have "display: block", then the issue disappears.

**Comment by josevalim** [comment] 2017-12-22 10:26
I am closing this for now as I believe the issue is in using a block element inside an inline one - it is not something specific to phoenix_html.

**Closed by josevalim** 2017-12-22 10:26 UTC
